import {
  BarChart3, Bell, Briefcase, Building2, Calendar, CalendarClock, Camera, Check, CheckCircle,
  ChevronDown, ChevronRight, ChevronUp, CircleCheck, CircleDollarSign, CircleHelp, CircleOff, ClipboardList, Clock,
  Columns3, Download, ExternalLink, Eye, EyeOff, File, FileSpreadsheet, FileText, Filter,
  FolderOpen, Globe, History, Image, Info, LayoutDashboard, ListFilter, Lock, LogIn, LogOut,
  Mail, Menu, Moon, Pencil, Phone, PieChart, Plus, PlusCircle, Power, Printer, Receipt, RefreshCw,
  RotateCcw, Save, ScrollText, Search, Share2, Shield, ShieldCheck, ShoppingBag, SlidersHorizontal,
  Store, Sun, Trash2, TrendingDown, TrendingUp, TriangleAlert, Upload, User, UserCog, Users, Wallet, X,
  ChevronsLeft, ChevronsRight,
} from "lucide-react";

const MAP = {
  "layout-dashboard": LayoutDashboard,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "pie-chart": PieChart,
  "file-spreadsheet": FileSpreadsheet,
  "scroll-text": ScrollText,
  users: Users,
  "user-cog": UserCog,
  logout: LogOut,
  "log-out": LogOut,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  wallet: Wallet,
  bell: Bell,
  sun: Sun,
  menu: Menu,
  moon: Moon,
  x: X,
  plus: Plus,
  "plus-circle": PlusCircle,
  pencil: Pencil,
  "trash-2": Trash2,
  eye: Eye,
  "eye-off": EyeOff,
  search: Search,
  "columns-3": Columns3,
  "rotate-ccw": RotateCcw,
  download: Download,
  "bar-chart-3": BarChart3,
  "circle-dollar-sign": CircleDollarSign,
  calendar: Calendar,
  "calendar-clock": CalendarClock,
  "list-filter": ListFilter,
  "file-text": FileText,
  info: Info,
  "triangle-alert": TriangleAlert,
  "circle-help": CircleHelp,
  history: History,
  "circle-check": CircleCheck,
  upload: Upload,
  "folder-open": FolderOpen,
  "refresh-cw": RefreshCw,
  clock: Clock,
  shield: Shield,
  "shield-check": ShieldCheck,
  "alert-circle": TriangleAlert,
  power: Power,
  "sliders-horizontal": SlidersHorizontal,
  "circle-off": CircleOff,
  filter: Filter,
  store: Store,
  save: Save,
  camera: Camera,
  image: Image,
  user: User,
  mail: Mail,
  phone: Phone,
  briefcase: Briefcase,
  "building-2": Building2,
  globe: Globe,
  check: Check,
  "check-circle": CheckCircle,
  lock: Lock,
  "chevron-right": ChevronRight,
  "chevrons-left": ChevronsLeft,
  "chevrons-right": ChevronsRight,
  "log-in": LogIn,
  printer: Printer,
  "share-2": Share2,
  "arrow-right": ChevronRight,
  "external-link": ExternalLink,
  "clipboard-list": ClipboardList,
  file: File,
  receipt: Receipt,
  "shopping-bag": ShoppingBag,
};

export function I({ name, size = 16 }) {
  const C = MAP[name] || Info;
  return <C size={size} strokeWidth={1.75} aria-hidden="true" />;
}
